baseURL = "https://main--aquamarine-bombolone-2e6487.netlify.app/"
languageCode = "en-us"
title = "Omar J Zant"
themes = "digit"
themesdir = "themes/digit/"
copyright = "Omar j Zant ©"


[params]
  name = "Omar J Zant"
  description = "Full Stack web Developper."
  initials = "O J Z"
  googleAnalytics = ""

  [[params.social]]
    name = "Twitter"
    link = "https://twitter.com/home"
    icon = "fab fa-twitter"

  [[params.social]]
    name = "Github"
    link = "https://github.com/omar-alzant"
    icon = "fab fa-github"

  [[params.social]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/omar-alzant-75566b1a3/"
    icon = "fab fa-linkedin-in"


[menu]
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 1

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    name = "Library"
    url = "/library/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4


[taxonomies]
  blog_tags = 'blog_tags'
  # project_tags = 'project_tags'


[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.highlight]
    # Choose from https://xyproto.github.io/splash/docs/all.html
    style = 'monokailight'